# Generated by Django 6.0.4 on 2026-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_servant',
            field=models.BooleanField(default=False, help_text='Volunteer servant role at the church', verbose_name='Is servant (خادم)'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_sport',
            field=models.CharField(blank=True, help_text='Which sport this coach mainly handles', max_length=30, verbose_name='Primary sport'),
        ),
    ]
