# Generated by Django 4.2.30 on 2026-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_servant_user_primary_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Parent email'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, help_text="Name of the player's parent or guardian", max_length=120, verbose_name='Parent name'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Parent phone'),
        ),
    ]
