# Generated by Django 5.0.6 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_parent_email_user_parent_name_user_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='odoo_id',
            field=models.PositiveIntegerField(blank=True, help_text='Primary key of the matching res.partner (or custom model) in Odoo.', null=True, unique=True, verbose_name='Odoo record ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='odoo_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last written from Odoo.', null=True, verbose_name='Last Odoo sync'),
        ),
    ]
