# Generated by Django 6.0.4 on 2026-04-25 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('event_type', models.CharField(choices=[('training', 'Training'), ('match', 'Match'), ('prayer', 'Prayer Meeting'), ('parent', 'Parent Activity'), ('camp', 'Camp'), ('other', 'Other Event')], max_length=20, verbose_name='Event type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_datetime', models.DateTimeField(verbose_name='Start')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('location', models.CharField(max_length=300, verbose_name='Location')),
                ('assigned_groups', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ParentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
