# Generated by Django 6.0.4 on 2026-04-25 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('table_tennis', 'Table Tennis')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=1, help_text='Goals=1, Basketball=2 or 3, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('table_tennis', 'Table Tennis')], max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('table_tennis', 'Table Tennis')], max_length=30, verbose_name='Sport')),
                ('age_group', models.CharField(blank=True, help_text='e.g. U-12, U-15, U-18', max_length=30, verbose_name='Age group')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('table_tennis', 'Table Tennis')], max_length=30)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
