# Generated by Django 4.2.30 on 2026-05-21 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('competition_type', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly')], default='league', max_length=20, verbose_name='Type')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('table_tennis', 'Table Tennis')], max_length=30, verbose_name='Sport')),
                ('season', models.CharField(blank=True, help_text='e.g. 2025-2026', max_length=30, verbose_name='Season')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='sports.competition', verbose_name='Competition'),
        ),
    ]
