# Generated by Django 6.0.4 on 2026-04-25 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, max_length=300, verbose_name='Title (Arabic)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_ar', models.TextField(blank=True, verbose_name='Content (Arabic)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'ordering': ['-created_at'],
            },
        ),
    ]
