# Generated by Django 5.0.6 on 2026-08-12 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English, optional)')),
                ('description_ar', models.CharField(blank=True, max_length=300, verbose_name='Description (Arabic)')),
                ('description_en', models.CharField(blank=True, max_length=300, verbose_name='Description (English, optional)')),
                ('icon', models.CharField(default='⭐', help_text='Single emoji shown on the slide.', max_length=8, verbose_name='Icon (emoji)')),
                ('image', models.ImageField(blank=True, help_text='Optional background photo. If empty, the gradient tint is used.', null=True, upload_to='carousel/', verbose_name='Image')),
                ('tint_from', models.CharField(default='#5A0F0F', help_text='Hex colour used as the top-left of the slide background.', max_length=9, verbose_name='Gradient start colour')),
                ('tint_to', models.CharField(default='#7A1C1C', help_text='Hex colour used as the bottom-right of the slide background.', max_length=9, verbose_name='Gradient end colour')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
