# Generated by Django 5.0.6 on 2026-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optional emoji shown on top of the slide. Leave empty for a clean image.', max_length=8, verbose_name='Icon (emoji, optional)'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, help_text='The main content of the slide. Recommended: at least 1200x600 landscape.', null=True, upload_to='carousel/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='tint_from',
            field=models.CharField(blank=True, default='#5A0F0F', help_text='Only used if no image is uploaded. Hex colour, top-left.', max_length=9, verbose_name='Fallback colour start'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='tint_to',
            field=models.CharField(blank=True, default='#7A1C1C', help_text='Only used if no image is uploaded. Hex colour, bottom-right.', max_length=9, verbose_name='Fallback colour end'),
        ),
    ]
