# Generated by Django 4.2.30 on 2026-05-24 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='سؤال')),
                ('option_a', models.CharField(max_length=200, verbose_name='الخيار أ')),
                ('option_b', models.CharField(max_length=200, verbose_name='الخيار ب')),
                ('option_c', models.CharField(max_length=200, verbose_name='الخيار ج')),
                ('option_d', models.CharField(max_length=200, verbose_name='الخيار د')),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('reference', models.CharField(blank=True, help_text='مثال: سفر يونان 1:17', max_length=120, verbose_name='المرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سؤال إنجيلي',
                'verbose_name_plural': 'الأسئلة الإنجيلية',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('total_days_completed', models.PositiveIntegerField(default=0)),
                ('last_completed_day', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.biblequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day', '-answered_at'],
                'indexes': [models.Index(fields=['user', '-day'], name='quiz_dailyq_user_id_7232b2_idx')],
                'unique_together': {('user', 'question', 'day')},
            },
        ),
    ]
