# Generated by Django 5.0.6 on 2026-06-01 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('bible_reference', models.CharField(help_text='Reference only, e.g. "John 15:1-8" — the text is not shown.', max_length=120, verbose_name='Bible reference')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily content',
                'verbose_name_plural': 'Daily content',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge progress',
                'verbose_name_plural': 'Challenge progress',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('daily_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dailychallenge.dailycontent', verbose_name='Daily content')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Choice')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dailychallenge.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='ChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_answers', to=settings.AUTH_USER_MODEL)),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailychallenge.choice')),
                ('daily_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dailychallenge.dailycontent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailychallenge.question')),
            ],
            options={
                'verbose_name': 'Challenge answer',
                'verbose_name_plural': 'Challenge answers',
                'ordering': ['question_id'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
