# Generated by Django 4.2.30 on 2026-05-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('evaluation', 'New evaluation'), ('session', 'New session'), ('news', 'News posted'), ('event', 'Upcoming event'), ('attendance', 'Attendance recorded'), ('system', 'System notice')], default='system', max_length=20, verbose_name='Kind')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.CharField(blank=True, max_length=400, verbose_name='Message')),
                ('url', models.CharField(blank=True, max_length=400, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
