# Generated by Django 6.0.4 on 2026-04-25 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('session_type', models.CharField(choices=[('training', 'Training'), ('prayer', 'Prayer Meeting'), ('match', 'Match'), ('event', 'Event')], max_length=20, verbose_name='Type')),
                ('sport', models.CharField(blank=True, max_length=30, verbose_name='Sport')),
                ('token', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Token')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this time the QR is invalid', null=True, verbose_name='Expires at')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is open')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='session_qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
